/**
 * Compare table — Phase 2 Package D (req 6.4), GM Portal's "Compare" action.
 *
 * A plain read-only table: Original Agreement / Revised Agreement with
 * Amendment / Generated by Whom, for every clause revision on this
 * agreement. Deliberately separate from AgreementCompare.tsx (the
 * existing side-by-side PDF + inline track-changes view used elsewhere) —
 * this is the simpler, table-only view the GM Dashboard links to.
 */
import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";

import { humanRole } from "../lib/roles";
import { api } from "../lib/api";

type CompareRow = {
  id: string;
  clause_label: string;
  original_text: string;
  revised_text: string;
  change_reason: string | null;
  status: string;
  generated_by_name: string | null;
  generated_by_role: string | null;
  created_at: string | null;
};

const STATUS_STYLES: Record<string, string> = {
  accepted: "bg-green-100 text-green-700 border-green-300",
  pending: "bg-amber-100 text-amber-700 border-amber-300",
  rejected: "bg-red-100 text-red-700 border-red-300",
};

export default function AgreementCompareTable() {
  const { id: agreementId } = useParams<{ id: string }>();
  const [rows, setRows] = useState<CompareRow[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!agreementId) return;
    let cancelled = false;
    (async () => {
      setLoading(true);
      setError(null);
      try {
        const { data } = await api.get(`/agreements/${agreementId}/compare-table`);
        if (!cancelled) setRows(data.rows ?? []);
      } catch {
        if (!cancelled) setError("Failed to load the compare table.");
      } finally {
        if (!cancelled) setLoading(false);
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [agreementId]);

  return (
    <div className="p-4">
      <div className="mb-3 flex items-center justify-between">
        <h1 className="text-lg font-semibold">Compare — Amended Clauses</h1>
        {agreementId && (
          <Link
            to={`/agreements/${agreementId}/compare`}
            className="rounded-lg border border-sky-300 bg-sky-50 px-3 py-1 text-sm text-sky-800 hover:bg-sky-100"
          >
            Open full Compare view →
          </Link>
        )}
      </div>

      {loading ? (
        <p className="text-sm text-gray-400">Loading…</p>
      ) : error ? (
        <p className="text-sm text-red-600">{error}</p>
      ) : rows.length === 0 ? (
        <p className="text-sm text-gray-400">No amended clauses on this agreement.</p>
      ) : (
        <div className="overflow-auto rounded border">
          <table className="min-w-[900px] w-full border-collapse text-sm">
            <thead>
              <tr className="bg-gray-100 text-left text-xs text-gray-600">
                <th className="border p-2 font-semibold">Clause</th>
                <th className="min-w-[220px] border p-2 font-semibold">Original Agreement</th>
                <th className="min-w-[220px] border p-2 font-semibold">Revised Agreement with Amendment</th>
                <th className="border p-2 font-semibold">Generated by Whom</th>
                <th className="border p-2 font-semibold">Status</th>
              </tr>
            </thead>
            <tbody>
              {rows.map((row) => (
                <tr key={row.id}>
                  <td className="border p-2 align-top text-xs text-gray-700">{row.clause_label}</td>
                  <td className="border p-2 align-top text-xs text-gray-500">
                    <span className="whitespace-pre-wrap break-words leading-relaxed">
                      {row.original_text}
                    </span>
                  </td>
                  <td className="border p-2 align-top text-xs text-gray-900">
                    <span className="whitespace-pre-wrap break-words leading-relaxed font-medium">
                      {row.revised_text}
                    </span>
                    {row.change_reason && (
                      <div className="mt-1 text-[11px] italic text-gray-500">
                        Reason: {row.change_reason}
                      </div>
                    )}
                  </td>
                  <td className="border p-2 align-top text-xs text-gray-700">
                    {row.generated_by_name ?? "Unknown"}
                    {row.generated_by_role && (
                      <div className="text-[11px] text-gray-400">{humanRole(row.generated_by_role)}</div>
                    )}
                  </td>
                  <td className="border p-2 align-top text-xs">
                    <span
                      className={`rounded-full border px-2 py-0.5 text-[10px] font-semibold capitalize ${
                        STATUS_STYLES[row.status] ?? "bg-gray-100 text-gray-600 border-gray-300"
                      }`}
                    >
                      {row.status}
                    </span>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
}
