/**
 * Compare table — GM Portal's "Compare" action.
 *
 * A plain table: Original Agreement / Revised Agreement with Amendment /
 * Generated by Whom, covering formal clause revisions (always shown) plus
 * any admin-entered field a reviewer specifically commented on.
 *
 * 2026-09-02 client feedback reversed the 2026-08-26 per-row decision UI:
 * "The GM will not review each clause item by item ... provide a single
 * overall approval option at the bottom" — Approve / Approved with
 * comments / Rejected with comments now resolve GM's whole review step at
 * once (same /workflow/{step}/approve|return endpoints WorkflowReview.tsx
 * uses), not a per-row action. Same feedback: "If there are no comments
 * from Accounts or OM, there is no need to display all the clauses added
 * by Admin below" — the backend (build_compare_rows) now only returns a
 * field row when a non-admin reviewer left a comment referencing it;
 * clause revisions are always shown (each is a deliberate, formal edit).
 * Each row carries the reviewer comment(s) that got it shown, so GM sees
 * why without opening the full Clause Review matrix.
 */
import { useEffect, useState } from "react";
import { useParams } from "react-router-dom";

import { useToast } from "../components/Toast";
import { humanRole } from "../lib/roles";
import { api } from "../lib/api";
import { useAuth } from "../stores/auth";

type ReviewerComment = {
  author_name: string | null;
  author_role: string | null;
  comment_text: string;
};

type CompareRow = {
  id: string;
  kind: "field" | "clause_revision";
  field_id: string | null;
  clause_label: string;
  original_text: string;
  revised_text: string;
  change_reason: string | null;
  status: string;
  generated_by_name: string | null;
  generated_by_role: string | null;
  created_at: string | null;
  reviewer_comments: ReviewerComment[];
};

type WorkflowStep = {
  id: string;
  step_name: string;
  step_order: number;
  role_required: string;
  status: string;
};

const isResolutionStepName = (name: string) => name.startsWith("Resolution");

export default function AgreementCompareTable() {
  const { id: agreementId } = useParams<{ id: string }>();
  const toast = useToast();
  const role = useAuth((s) => s.user?.role);

  const [rows, setRows] = useState<CompareRow[]>([]);
  const [steps, setSteps] = useState<WorkflowStep[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const [commentText, setCommentText] = useState("");
  const [busy, setBusy] = useState(false);

  const load = async () => {
    if (!agreementId) return;
    setLoading(true);
    setError(null);
    try {
      const [compareResp, summaryResp] = await Promise.all([
        api.get(`/agreements/${agreementId}/compare-table`),
        api.get(`/workflow/agreements/${agreementId}`),
      ]);
      setRows(compareResp.data.rows ?? []);
      setSteps(summaryResp.data.steps ?? []);
    } catch {
      setError("Failed to load the compare table.");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    void load();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [agreementId]);

  const myStep = steps.find((s) => s.role_required === role) ?? null;
  const myStepChainSteps = steps.filter(
    (s) => isResolutionStepName(s.step_name) === (myStep ? isResolutionStepName(myStep.step_name) : false)
  );
  const priorStep = myStep ? myStepChainSteps.find((s) => s.step_order === myStep.step_order - 1) : null;
  const myStepUnlocked = !myStep || myStep.step_order <= 1 || priorStep?.status === "approved";
  const myStepApproved = myStep?.status === "approved";
  const myStepRejected = myStep?.status === "returned";
  const canDecide = role !== "admin" && !!myStep && myStep.status === "pending" && myStepUnlocked;

  const decideStep = async (action: "approve" | "return", withComment: boolean) => {
    if (!myStep || busy) return;
    if ((withComment || action === "return") && !commentText.trim()) {
      toast.error(action === "return" ? "Please enter a reason for rejection." : "Please enter a comment.");
      return;
    }
    setBusy(true);
    try {
      await api.post(
        `/workflow/${myStep.id}/${action}`,
        action === "return"
          ? { comment_text: commentText }
          : withComment
            ? { comment_text: commentText }
            : undefined,
      );
      toast.success(
        action === "return" ? "Rejected. Sent back to Admin for revision." : "Approved."
      );
      setCommentText("");
      await load();
    } catch (err: unknown) {
      const e = err as { response?: { data?: { detail?: string } } };
      toast.error(e?.response?.data?.detail ?? "Failed to record decision.");
    } finally {
      setBusy(false);
    }
  };

  return (
    <div className="p-4">
      <h1 className="mb-3 text-lg font-semibold">Compare — Original vs Revised Agreement</h1>

      {loading ? (
        <p className="text-sm text-gray-400">Loading…</p>
      ) : error ? (
        <p className="text-sm text-red-600">{error}</p>
      ) : (
        <>
          {rows.length === 0 ? (
            <p className="mb-4 text-sm text-gray-400">
              No reviewer comments or proposed clause edits on this agreement — nothing flagged for your attention.
            </p>
          ) : (
            <div className="mb-4 overflow-auto rounded border">
              <table className="min-w-[1000px] w-full border-collapse text-sm">
                <thead>
                  <tr className="bg-gray-100 text-left text-xs text-gray-600">
                    <th className="border p-2 font-semibold">Clause</th>
                    <th className="min-w-[200px] border p-2 font-semibold">Original Agreement</th>
                    <th className="min-w-[200px] border p-2 font-semibold">Revised Agreement with Amendment</th>
                    <th className="border p-2 font-semibold">Generated by Whom</th>
                    <th className="min-w-[220px] border p-2 font-semibold">Reviewer Comments</th>
                  </tr>
                </thead>
                <tbody>
                  {rows.map((row) => (
                    <tr key={row.id}>
                      <td className="border p-2 align-top text-xs text-gray-700">{row.clause_label}</td>
                      <td className="border p-2 align-top text-xs text-gray-500">
                        <span className="whitespace-pre-wrap break-words leading-relaxed">{row.original_text}</span>
                      </td>
                      <td className="border p-2 align-top text-xs text-gray-900">
                        <span className="whitespace-pre-wrap break-words leading-relaxed font-medium">
                          {row.revised_text}
                        </span>
                        {row.change_reason && (
                          <div className="mt-1 text-[11px] italic text-gray-500">Reason: {row.change_reason}</div>
                        )}
                      </td>
                      <td className="border p-2 align-top text-xs text-gray-700">
                        {row.generated_by_name ?? "Unknown"}
                        {row.generated_by_role && (
                          <div className="text-[11px] text-gray-400">{humanRole(row.generated_by_role)}</div>
                        )}
                      </td>
                      <td className="border p-2 align-top text-xs">
                        {row.reviewer_comments.length === 0 ? (
                          <span className="text-gray-300">—</span>
                        ) : (
                          <div className="space-y-1.5">
                            {row.reviewer_comments.map((c, i) => (
                              <div key={i} className="rounded border border-amber-200 bg-amber-50 p-1.5">
                                <div className="text-[10px] font-semibold text-amber-800">
                                  {c.author_name ?? "Unknown"}
                                  {c.author_role ? ` · ${humanRole(c.author_role)}` : ""}
                                </div>
                                <div className="text-gray-700">{c.comment_text}</div>
                              </div>
                            ))}
                          </div>
                        )}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}

          {/* Single overall decision, at the bottom — not per row. */}
          {role !== "admin" && myStep && (
            <div className="rounded border p-3">
              <h3 className="mb-2 font-semibold">Review Action</h3>
              {myStepApproved ? (
                <span className="rounded border border-green-300 bg-green-100 px-4 py-2 text-sm font-medium text-green-700">
                  ✓ Approved
                </span>
              ) : myStepRejected ? (
                <span className="rounded border border-red-300 bg-red-100 px-4 py-2 text-sm font-medium text-red-700">
                  ✗ Rejected — awaiting Admin revision
                </span>
              ) : !myStepUnlocked ? (
                <span className="rounded border border-gray-300 bg-gray-100 px-4 py-2 text-sm text-gray-500">
                  Waiting for {priorStep ? humanRole(priorStep.role_required) : "the previous reviewer"} to approve
                </span>
              ) : (
                <div className="grid gap-2">
                  <textarea
                    className="rounded border p-2 text-sm"
                    rows={3}
                    placeholder="Comment (required for 'with comments' / reject)"
                    value={commentText}
                    onChange={(e) => setCommentText(e.target.value)}
                    disabled={!canDecide || busy}
                  />
                  <div className="flex flex-wrap gap-2">
                    <button
                      className="rounded bg-green-700 px-4 py-2 text-white disabled:opacity-50"
                      disabled={!canDecide || busy}
                      onClick={() => void decideStep("approve", false)}
                    >
                      {busy ? "Working…" : "Approve"}
                    </button>
                    <button
                      className="rounded bg-sky-700 px-4 py-2 text-white disabled:opacity-50"
                      disabled={!canDecide || busy}
                      onClick={() => void decideStep("approve", true)}
                    >
                      {busy ? "Working…" : "Approved with comments"}
                    </button>
                    <button
                      className="rounded bg-red-700 px-4 py-2 text-white disabled:opacity-50"
                      disabled={!canDecide || busy}
                      onClick={() => void decideStep("return", true)}
                    >
                      {busy ? "Working…" : "Rejected with comments"}
                    </button>
                  </div>
                </div>
              )}
            </div>
          )}
        </>
      )}
    </div>
  );
}
