/**
 * Compare table — Phase 2 Package D (req 4), GM Portal's "Compare" action.
 *
 * A plain read-only table: Original Agreement / Revised Agreement with
 * Amendment / Generated by Whom, covering every filled-in field value plus
 * any formal clause revisions on this agreement (see the backend's
 * compare-table endpoint). Deliberately separate from AgreementCompare.tsx
 * (the existing side-by-side PDF + inline track-changes view used
 * elsewhere) — this is the simpler, table-only view req 4 describes.
 *
 * Req 7: "for any roles except admin", the bottom of this page carries the
 * Approved / Approved with comments / Rejected with comments actions for
 * whoever's own reviewer step on this agreement is currently actionable —
 * this is where GM (and any other reviewer who lands here) makes their
 * decision, not a separate action on the dashboard row.
 */
import { useEffect, useState } from "react";
import { useParams } from "react-router-dom";

import { useToast } from "../components/Toast";
import { humanRole } from "../lib/roles";
import { api } from "../lib/api";
import { useAuth } from "../stores/auth";

type CompareRow = {
  id: string;
  kind: "field" | "clause_revision";
  clause_label: string;
  original_text: string;
  revised_text: string;
  change_reason: string | null;
  status: string;
  generated_by_name: string | null;
  generated_by_role: string | null;
  created_at: string | null;
};

type WorkflowStep = {
  id: string;
  step_name: string;
  step_order: number;
  role_required: string;
  status: string;
};

const STATUS_STYLES: Record<string, string> = {
  accepted: "bg-green-100 text-green-700 border-green-300",
  entered: "bg-sky-100 text-sky-700 border-sky-300",
  pending: "bg-amber-100 text-amber-700 border-amber-300",
  rejected: "bg-red-100 text-red-700 border-red-300",
};

const STATUS_TEXT: Record<string, string> = {
  entered: "Entered",
};

const isResolutionStepName = (name: string) => name.startsWith("Resolution");

export default function AgreementCompareTable() {
  const { id: agreementId } = useParams<{ id: string }>();
  const toast = useToast();
  const role = useAuth((s) => s.user?.role);

  const [rows, setRows] = useState<CompareRow[]>([]);
  const [steps, setSteps] = useState<WorkflowStep[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [commentText, setCommentText] = useState("");
  const [busy, setBusy] = useState(false);

  const load = async () => {
    if (!agreementId) return;
    setLoading(true);
    setError(null);
    try {
      const [compareResp, summaryResp] = await Promise.all([
        api.get(`/agreements/${agreementId}/compare-table`),
        api.get(`/workflow/agreements/${agreementId}`),
      ]);
      setRows(compareResp.data.rows ?? []);
      setSteps(summaryResp.data.steps ?? []);
    } catch {
      setError("Failed to load the compare table.");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    void load();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [agreementId]);

  const myStep = steps.find((s) => s.role_required === role) ?? null;
  const myStepChainSteps = steps.filter(
    (s) => isResolutionStepName(s.step_name) === (myStep ? isResolutionStepName(myStep.step_name) : false)
  );
  const priorStep = myStep ? myStepChainSteps.find((s) => s.step_order === myStep.step_order - 1) : null;
  const myStepUnlocked = !myStep || myStep.step_order <= 1 || priorStep?.status === "approved";
  const canDecide = role !== "admin" && myStep && myStep.status === "pending" && myStepUnlocked;

  const approve = async (withComment: boolean) => {
    if (!myStep) return;
    if (withComment && !commentText.trim()) {
      toast.error("Please enter a comment.");
      return;
    }
    setBusy(true);
    try {
      await api.post(`/workflow/${myStep.id}/approve`, withComment ? { comment_text: commentText } : undefined);
      toast.success(withComment ? "Approved with comments." : "Approved.");
      setCommentText("");
      await load();
    } catch (err: unknown) {
      const e = err as { response?: { data?: { detail?: string } } };
      toast.error(e?.response?.data?.detail ?? "Failed to approve.");
    } finally {
      setBusy(false);
    }
  };

  const reject = async () => {
    if (!myStep) return;
    if (!commentText.trim()) {
      toast.error("Please enter a reason for rejection.");
      return;
    }
    setBusy(true);
    try {
      await api.post(`/workflow/${myStep.id}/return`, { comment_text: commentText });
      toast.success("Rejected. Sent back to Admin for revision.");
      setCommentText("");
      await load();
    } catch (err: unknown) {
      const e = err as { response?: { data?: { detail?: string } } };
      toast.error(e?.response?.data?.detail ?? "Failed to reject.");
    } finally {
      setBusy(false);
    }
  };

  return (
    <div className="p-4">
      <h1 className="mb-3 text-lg font-semibold">Compare — Original vs Revised Agreement</h1>

      {loading ? (
        <p className="text-sm text-gray-400">Loading…</p>
      ) : error ? (
        <p className="text-sm text-red-600">{error}</p>
      ) : rows.length === 0 ? (
        <p className="text-sm text-gray-400">No admin-entered content on this agreement yet.</p>
      ) : (
        <div className="overflow-auto rounded border">
          <table className="min-w-[900px] w-full border-collapse text-sm">
            <thead>
              <tr className="bg-gray-100 text-left text-xs text-gray-600">
                <th className="border p-2 font-semibold">Clause</th>
                <th className="min-w-[220px] border p-2 font-semibold">Original Agreement</th>
                <th className="min-w-[220px] border p-2 font-semibold">Revised Agreement with Amendment</th>
                <th className="border p-2 font-semibold">Generated by Whom</th>
                <th className="border p-2 font-semibold">Status</th>
              </tr>
            </thead>
            <tbody>
              {rows.map((row) => (
                <tr key={row.id}>
                  <td className="border p-2 align-top text-xs text-gray-700">{row.clause_label}</td>
                  <td className="border p-2 align-top text-xs text-gray-500">
                    <span className="whitespace-pre-wrap break-words leading-relaxed">
                      {row.original_text}
                    </span>
                  </td>
                  <td className="border p-2 align-top text-xs text-gray-900">
                    <span className="whitespace-pre-wrap break-words leading-relaxed font-medium">
                      {row.revised_text}
                    </span>
                    {row.change_reason && (
                      <div className="mt-1 text-[11px] italic text-gray-500">
                        Reason: {row.change_reason}
                      </div>
                    )}
                  </td>
                  <td className="border p-2 align-top text-xs text-gray-700">
                    {row.generated_by_name ?? "Unknown"}
                    {row.generated_by_role && (
                      <div className="text-[11px] text-gray-400">{humanRole(row.generated_by_role)}</div>
                    )}
                  </td>
                  <td className="border p-2 align-top text-xs">
                    <span
                      className={`rounded-full border px-2 py-0.5 text-[10px] font-semibold capitalize ${
                        STATUS_STYLES[row.status] ?? "bg-gray-100 text-gray-600 border-gray-300"
                      }`}
                    >
                      {STATUS_TEXT[row.status] ?? row.status}
                    </span>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}

      {canDecide && (
        <div className="mt-4 rounded border border-sky-200 bg-sky-50/60 p-3">
          <h2 className="mb-1 text-xs font-semibold uppercase tracking-wide text-sky-800">Your Decision</h2>
          <textarea
            className="w-full rounded border p-2 text-xs"
            rows={2}
            placeholder="Comment (required for 'Approved with comments' or 'Rejected with comments')"
            value={commentText}
            onChange={(e) => setCommentText(e.target.value)}
            disabled={busy}
          />
          <div className="mt-2 flex flex-wrap gap-2">
            <button
              className="rounded bg-green-600 px-3 py-1.5 text-xs font-medium text-white disabled:opacity-50"
              disabled={busy}
              onClick={() => approve(false)}
            >
              Approved
            </button>
            <button
              className="rounded bg-green-100 px-3 py-1.5 text-xs font-medium text-green-800 disabled:opacity-50"
              disabled={busy}
              onClick={() => approve(true)}
            >
              Approved with comments
            </button>
            <button
              className="rounded bg-red-100 px-3 py-1.5 text-xs font-medium text-red-800 disabled:opacity-50"
              disabled={busy}
              onClick={reject}
            >
              Rejected with comments
            </button>
          </div>
        </div>
      )}
    </div>
  );
}
